repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: 'v5.0.0'
    hooks:
      - id: 'check-added-large-files'
      - id: 'check-case-conflict'
      - id: 'check-json'
      - id: 'check-merge-conflict'
      - id: 'check-symlinks'
      - id: 'check-toml'
      - id: 'check-yaml'
      - id: 'detect-private-key'
      - id: 'end-of-file-fixer'
        exclude_types: ['json']
      - id: 'mixed-line-ending'
      - id: 'trailing-whitespace'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.12.2'
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
